### ISSUE TITLE
升级到Rails 7.1后报错

### ISSUE THREAD

**Issue by clwy-cn** [rails-engine/action-store#18]
```sh
<internal:/Users/liu/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- action (LoadError)
```

**Comment by huacnlee** [comment]
给出更多的错误信息。

Homeland 那边项目我也才升级过，没有遇到问题

**Comment by clwy-cn** [comment]
可以做一个简单的尝试，直接建一个新项目

```
rails new rails7release -d postgresql 
```

这时候，`rails s`或者 `rails c`，都是没有问题的。

接着在gemfile中加入

```
gem "action-store"
```

并且`bundle install`，现在无论是`rails s`或者 `rails c`，全部报错

<img width="1461" alt="image" src="https://github.com/rails-engine/action-store/assets/57120683/3cdf5c08-1bbf-4ba5-b699-06b33008764e">


<img width="1458" alt="image" src="https://github.com/rails-engine/action-store/assets/57120683/99a250c8-77bc-4bea-a82e-b67199de2f70">
ra

**Comment by huacnlee** [comment]
好的 我下午试一下

Dong Liu ***@***.***>于2023年10月6日 周五下午12:04写道：

**Comment by huacnlee** [comment]
https://github.com/rails-engine/action-store/releases/tag/v1.1.3

**Comment by clwy-cn** [comment]
👍 👍 👍 ，可以用了
